server {
    listen 443 ssl http2;
    server_name app.nisolution.co.th;
    include /etc/nginx/infra/ssl.conf;
    access_log /var/log/nginx/app.access.log main_ext;

    location / {
        proxy_pass http://legacy_app/;
        include /etc/nginx/infra/proxy.conf;
        proxy_set_header Accept-Encoding "";
    }
}
