server {
    listen 443 ssl http2;
    server_name n8n.nisolution.co.th;
    include /etc/nginx/infra/ssl.conf;
    access_log /var/log/nginx/n8n.access.log main_ext;

    # webhook ของ n8n ต้องเปิด public
    location ~ ^/(webhook|webhook-test|webhook-waiting)/ {
        proxy_pass http://n8n;
        include /etc/nginx/infra/ws.conf;
    }

    # หน้า editor: แนะนำให้เปิดเฉพาะ IP ออฟฟิศ / VPN
    location / {
        # allow 203.0.113.10;     # IP ออฟฟิศ
        # allow 192.168.88.0/24;
        # deny all;
        proxy_pass http://n8n;
        include /etc/nginx/infra/ws.conf;
    }
}
