server {
    listen 443 ssl http2;
    server_name zabbix.nisolution.co.th;
    include /etc/nginx/infra/ssl.conf;
    location / {
        proxy_pass http://zbx_web/;
        include /etc/nginx/infra/ws.conf;
    }
}

server {
    listen 443 ssl http2;
    server_name api-zabbix.nisolution.co.th;
    include /etc/nginx/infra/ssl.conf;
    location / {
        proxy_pass http://zbx_api/;
        include /etc/nginx/infra/ws.conf;
    }
    location /web-service/ {
        proxy_pass http://zbx_ws/;
        include /etc/nginx/infra/ws.conf;
    }
}

server {
    listen 443 ssl http2;
    server_name monitor-zb.nisolution.co.th;
    include /etc/nginx/infra/ssl.conf;
    location / {
        proxy_pass http://zbx_monitor/;
        include /etc/nginx/infra/ws.conf;
    }
}
