# wildcard *.nisolution.co.th (ไฟล์ cert ไม่อยู่ใน Git)
ssl_certificate         /etc/nginx/ssl/fullchain_nisolution.crt;
ssl_certificate_key     /etc/nginx/ssl/star_nisolution_co_th.key;
ssl_trusted_certificate /etc/nginx/ssl/ca-bundle.crt;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
